#!/bin/sh
SCRIPT_DIR=`dirname $0`

SBT_OPTS="-Xms512M -Xmx1024M -Xss1M"
SBT_OPTS="$SBT_OPTS -XX:MaxPermSize=200M -XX:ReservedCodeCacheSize=60M"
SBT_OPTS="$SBT_OPTS -XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
SBT_OPTS="$SBT_OPTS -Dsbt.global.base=$SCRIPT_DIR/sbt"
SBT_OPTS="$SBT_OPTS -Dsbt.ivy.home=$SCRIPT_DIR/sbt/repository"

SBT_JAR="$SCRIPT_DIR/sbt/sbt-launch.jar"

java $JAVA_OPTS $SBT_OPTS -jar $SBT_JAR "$@"
